### ISSUE TITLE
Push notification channels?

### ISSUE THREAD

**Issue by giorgio79** [dpi/courier#16]
Would be fantastic to have push based channels as well:
Some D7 examples (smartphones and browsers)
https://www.drupal.org/project/push_notifications
https://www.drupal.org/sandbox/mantix/2567811

**Comment by dpi** [comment]
Sounds like a reasonable request. However it is the responsibility of modules such as push_notifications to implement a simple plugin for Courier. It isn't in my interest to include channel specific logic in the main module other than core provided channels (Drupal email).

I am happy to help if third party modules need assistance in implementing such a plugin.

**Comment by dpi** [comment]
Looks like you created an [issue](https://www.drupal.org/node/2626886) for push_notifications project. Thanks.
