### ISSUE TITLE
Provide "Configure" routes if possible on Courier modules

### ISSUE THREAD

**Issue by mccrodp** [dpi/courier#17]
![configure-module-routes](https://cloud.githubusercontent.com/assets/559938/11747187/b90ecdb0-a019-11e5-9f6d-92becbdc5ee5.png)

As with Google Analytics above, if there are any associated Configure URLs to the separate Courier modules, perhaps they should have a route.

Also, should there be Courier related links to "Courier Compose"? I have to look into the yaml to find the path "/courier/compose". Is it linked somewhere via the UI, e.g. Content or Structure (guessing the latter may be better as there is no backend)

**Comment by dpi** [comment]
Sounds reasonable. Just need to add route to info.yml.

The compose links appear adjacent to the Add content link in the main menu navigation block outside of administration. Im sure we can improve the discoverability with better documentation.

**Comment by mccrodp** [comment]
![send-message-tab](https://cloud.githubusercontent.com/assets/559938/11747865/7678f724-a01d-11e5-8073-c72e8f8471f2.png)

Ahh I saw it eventually, thanks. I had to enable Bartik to see it as my theme didn't use the Tools block.
How about adding a "Send Message" local task beside "Add Content"? Or anywhere else more suitable?

I can do this in a simple PR next week as running out of time today :)

**Comment by dpi** [comment]
It wouldnt make sense as that route is both Node-specific and node.module dependent. The best route would be in a Courier specific route, unfortunately there is only Configuration routes.

Fortunately the Courier Composer module is primarily targeted as a debugging tool or one-off message, so a permanent menu button isn't important.

I imagine if Courier provided a detailed listing of all messages in its sending queue, then the button could be placed as a local action on that page. Right now basic sending queue info is exposed as a single line item on site report.

**Comment by mccrodp** [comment]
Yep, that's true, this wouldn't work.

If it's a debugging tool, perhaps under "Development" at "/admin/config/development/courier", somewhere anyways you think is best fit would really help I think...

**Comment by dpi** [comment]
I will keep things obscure for now and wait for an appropriate Courier list page to attach the local task. I think it is appropriate to have 'Send message' emulate Node.modules 'Add content' route and default menu item.

**Comment by mccrodp** [comment]
Ok, sounds like a plan. 

If Courier integrated with Message module, it could have the backend it needs to store or event just "log" messages sent through Courier. Then on Messages tab: "admin/content/messages", the "Add Message" or "Send Message" local task would fit perfectly.
