### ISSUE TITLE
Add delimiters to "Available tokens" on Courier Compose form?

### ISSUE THREAD

**Issue by mccrodp** [dpi/courier#18]
![token-delimiters](https://cloud.githubusercontent.com/assets/559938/11747337/9f08d11c-a01a-11e5-97f6-8719c42d58da.png)

It's not entirely obvious to me what the tokens are here or how someone would use them in D8.

"Available tokens: identity, site, date, current-user"

i.e. - To use _current-user_, is it _[current-user]_?

Should this be "Available tokens: [identity], [site], [date], [current-user]"?

**Comment by dpi** [comment]
If you have [Token](https://drupal.org/project/token) module installed you will get an improved UI for token lists!

The fallback token list can use improvement with square brackets. In addition to better documentation for suggesting site builder to install Token contrib module.

<img width="658" alt="tokenui" src="https://cloud.githubusercontent.com/assets/21850/11747912/c2d4a4f4-a060-11e5-9b32-baf9c25d59ab.png">

**Comment by mccrodp** [comment]
Sounds good to me, thanks! Great job in general by the way, some body of work in all of this. I'll be looking through the Access Control you have in place here when I eventually get back to Message UI! :)

**Comment by dpi** [comment]
Thanks! These are good UX improvements.

There is not a lot of access control as Courier is mostly an API module. The only access specific code that comes to mind is if you take advantage of the Template Collection UI. The AJAX form callback requires you to add your own hook_entity_access checking for $operation == 'templates'. [RNG](https://github.com/dpi/rng)'s rng.module and [Courier System](https://github.com/dpi/courier)'s courier_system.module implements this access check.

**Comment by mccrodp** [comment]
Oh ok...I saw the _ComposeAccessCheck_ class and presumed this may be useful. Will take a proper look then at some stage at the above mentions.

**Comment by dpi** [comment]
Ah, I would avoid anything in the submodules as I dont expect them to be enabled.

**Comment by edurenye** [comment]
What about having something like the following when you don't have the token module installed:
![detailed-tokens](https://cloud.githubusercontent.com/assets/6824576/14556666/8baecf30-02f9-11e6-9ce2-e95d3403d099.png)

Also I agree to add a suggestion to install the token module.

**Comment by dpi** [comment]
@edurenye its a reasonable suggestion, if overwhelming. I'd prefer if site builders would just install Token module. Since site users may get confused about the purpose of many tokens.

**Comment by dpi** [comment]
![rawtoken](https://cloud.githubusercontent.com/assets/21850/14704889/7a30bada-07e9-11e6-9316-103050366b49.jpg)

Improved raw global token list (when token.module unavailable) and documented integration of token.module in README.
