### ISSUE TITLE
Courier TemplateCollectionList element does not work with Drupal 8.1

### ISSUE THREAD

**Issue by dpi** [dpi/courier#21]
Courier template ajax widget seems to have stopped working in 8.1 (as at 8.1.0-rc1)

**Edit (Thu Apr 21 2016):**  For reference: this bug does not affect Drupal core 8.0, only 8.1 and later.

**Comment by edurenye** [comment]
This is a core issue: [https://www.drupal.org/node/2705327](https://www.drupal.org/node/2705327)

**Comment by dpi** [comment]
Wow thanks! Hadn't had the time to look into this yet.

**Comment by dpi** [comment]
Ive applied the patch and it seems to have gotten the form working, it will save etc.

However if I press the "Email" template button to reload the template again in the same request, nothing happens.

In addition to this, the token list is not loading:

**Expected:**

![mg-ok](https://cloud.githubusercontent.com/assets/21850/14515305/54b21d94-022b-11e6-8ce5-9631fa7248b8.png)

**Got:**

<img width="481" alt="mg" src="https://cloud.githubusercontent.com/assets/21850/14515284/0ee0f588-022b-11e6-89c1-463f94b6edda.png">

It seems only the first request is processed? The network requests appear to be coming through in my Firefox console.

This could of course be an issue with the Courier js

**Comment by edurenye** [comment]
Fixed both things, was not really a core issue as jquery object is not supported, so here is the pull request #27

**Comment by dpi** [comment]
Fortunately https://www.drupal.org/node/2705327 can be fixed on our side.

However [Method removing expired drupalSettings.ajax tries to remove settings when there is no ajax defined](https://www.drupal.org/node/2700495) is actually the only remaining issue that I cannot fix. Its causing the TemplateCollectionList element to prevent any more AJAX calls after two are made. (Edit: See #28)
