### ISSUE TITLE
Slack / Mattermost integration

### ISSUE THREAD

**Issue by mirodietiker** [dpi/courier#33]
We are using Mattermost and i would love to see some events / notifications propagated to our mattermost channel.

Sure, i guess, can be a separate module, say courier_mattermost.
It's a trivial REST POST resource with a key and a body.
We can make the key globally configurable for now.

The difference here is that it's a channel and not a message to an individual. So it is not a full replacement for the direct message to the individual and more an additional notification.

With our proposed in TMGMT courier integration we would expect to simply add a new template collection to the same trigger.

**Comment by dpi** [comment]
I can help out, but I dont think I be including channels in Courier core that Drupal core doesnt natively support.

**Comment by dpi** [comment]
From what I understand Mattermost is Slack API-compatible?

https://github.com/maknz/slack would reduce the complexity of the integration

**Comment by mirodietiker** [comment]
Yeah it is Slack compatible.

But just posting to the API is so much simple... It feels kinda overkill to use a library for that.
I guess the access key settings form is the most complex part. ;-)

**Comment by dpi** [comment]
I think if I were doing the integration, I would also create a new identity type, where each identity mapped to one of the Slack/MM channels. That way you would target the sendMessage identity at the Slack channel, as you wouldnt target a Drupal user (?).

**Comment by mirodietiker** [comment]
Yeah, ability to target a channel would make sense. Or also a private conversation.
But again since the recipient is a different identity, you tell me i need to write code to trigger that message?

We need to be able to add a second message instance to an existing code trigger with a recipient override to give the UI sense and flexibility.

**Comment by dpi** [comment]
You don't need a different template template collection.

If you are looking at the code from dpi/tmgmt#1. You would add the entity mapping to the Slack channel to the `$users` array in Notification service.

**Comment by dpi** [comment]
I whipped up something over lunch:

![slackcourier](https://cloud.githubusercontent.com/assets/21850/14860935/9d3d34e2-0cdd-11e6-8ec7-d680f0331caa.jpg)

**Comment by dpi** [comment]
I've put it up here: https://github.com/dpi/courier_slack

The code is very rough, only a couple of hours worth of work. I used the composer dependency to get on my feet faster.

If you're wish to improve the module I can add a co-maintainer. Since I do not have much free time for the near future.

**Comment by dpi** [comment]
Continue discussions at https://github.com/dpi/courier_slack

**Comment by mirodietiker** [comment]
Thank you, this is awesome. :-)
