### ISSUE TITLE
Email messaging to Contact Identities fails

### ISSUE THREAD

**Issue by auVeypor** [dpi/courier#40]
Hey @dpi,

We are trying to use your Identity module in combination with RNG and Courier to allow anonymous users to register for an event, however we have found that Courier fails when attempting to send an email to the Contact Identity.

The dblog error message lists: 

> No messages could be sent to <identityname>. No messages were generated.

Which is generated from the sendMessage function (/src/Service/CourierManager.php line 93)

If you could please advise, we would be grateful.

**Comment by robertpharries** [comment]
Hi @dpi,

I am a colleague of @auVeypor and with the given problem that we had with the messaging system for identity, I thought I would have a poke around and see if I could modify the Courier/Identity Contact modules to allow courier to send messages that are to Contact entity types, not just users.

After an hour or two of reading the code, I developed a solution, which included:
- Addition of Identity Contact channels (courier_email) in the config/install/courier.settings.yml file. This allowed Courier to to recognise Identity Contact as a Identity type for a message, and provides the appropriate method.
- Addition of an Identity Contact file in the Identity Channel in Courier, /src/plugin/identitychannel/courieremail/, which provides Courier with the methods to retrieve the name and the email address from the Identity Contact.
- With the retrieval of the email address in the previous point, there was no defined method in Identity Contact that performed this action, so I added a method, getEmail(), almost identical to that in the core Drupal User module.

I am more than happy to provide to you these changed files/modules if you are interested. Just let us know how you'd like us to do so if this is the case.

Thanks.

**Comment by dpi** [comment]
This issue should have been filed against [Identity](https://github.com/dpi/identity).

Keep in mind that: Identity is not fully supported (dpi/identity#1).

>  config/install/courier.settings.yml file.

This is managed by Courier settings UI already...

> Identity Contact file [...] with the methods to retrieve the name and the email address from the Identity Contact.

This file already exists... https://github.com/dpi/identity/blob/8.x-1.x/identity_contact/src/Plugin/IdentityChannel/CourierEmail/IdentityContact.php

> I am more than happy to provide to you these changed files/modules if you are interested. Just let us know how you'd like us to do so if this is the case.

If above comments do not address your concerns, feel free to post a PR to the Identity project.

**Comment by robertpharries** [comment]
Apologies for the incorrectly placed issue thread. Originally the error messages were generated by courier so that's what we took as the issue. 

In regards to the identity channel plugin, I have found that, and understand how it functions now. Plugins were something we were not familiar with but lesson learned.

For the courier.settings file I'm not sure on what you mean about it being managed by the UI. I have found the settings for courier in the site configuration but was unable to locate anything to do with identity. Would you be able to explain this further?

Overall I feel as if this is a bit of a non-issue now and the messaging is now functioning. Thanks for helping regardless of our misunderstanding.

**Comment by dpi** [comment]
> For the courier.settings file I'm not sure on what you mean about it being managed by the UI.

What I mean is there are no hidden settings in Courier, you are not required to make manual edits to YAML or site config. All settings are available in UI.

> but was unable to locate anything to do with identity.

_/admin/config/communication/courier_

![identc](https://cloud.githubusercontent.com/assets/21850/19557024/7c0e07c6-96f6-11e6-85d9-c8471a776eb7.jpg)

**Comment by auVeypor** [comment]
Holy kittens, this is still open. Apologies!
We got this all sorted out, so I'll close this!

Thanks for your help @dpi
